Barchart to fc
reaviz/reaviz pull request #25
Opened 2020-12-08 07:34 UTC by ynahmany

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Refactor BarChart component to Functional component.

## Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```

## Other information

2020-12-08 12:52 UTC, amcdnl requested changes
A few minor nits but AWESOME overall! 

Just double check all of the storybook stories for bar charts work as expected, these FC changes are a little more sticky than one might expect.

2020-12-08 12:52 UTC, amcdnl commented on src/BarChart/BarChart.tsx
> +      {(props) => renderChart(props)}
I think this could just be this:

```suggestion
      {renderChart}
```

2020-12-08 12:52 UTC, amcdnl commented on src/BarChart/BarChart.tsx
> +  const renderChart = (containerProps: ChartContainerChildProps) => {
I think you probably want to do `useCallback` on these for memoization.

2020-12-08 12:52 UTC, amcdnl commented on src/BarChart/BarChart.tsx
> +  const getKeyScale = (data, axis, isMultiSeries: boolean, width: number) => {
I need to move the `ChartContainer` to be a hook and then a lot of this code could just be memoized and no need for the `renderChart` method too. Just a side note for later.

2020-12-13 14:33 UTC, amcdnl commented
Any thoughts on the feedback?

2020-12-13 14:33 UTC, amcdnl commented on src/BarChart/StackedNormalizedBarChart.tsx
> +  console.log('=================');
Need to remove console.

2020-12-13 14:42 UTC, amcdnl commented
On the issues w/ stories - this might be helpful - https://github.com/reaviz/reaviz/issues/13 - the parent props item.

2020-12-13 17:44 UTC, ynahmany commented
@amcdnl I encounter several issues, so I moved to a new PR, working with some more precise order(starting from a.b.c..).
* keys issue on stories.
* some of the stories was not fully loaded.

2020-12-13 18:12 UTC, amcdnl commented
Sounds good - if you are doing a anew pr maybe lets close this?

2020-12-13 19:57 UTC, closed without merging