Heatmap to fc
reaviz/reaviz pull request #29
Opened 2020-12-24 17:34 UTC by ynahmany

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ X] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Convert Heatmap folder to be functional components.

## Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```

## Other information
@amcdnl I need some help with `HeatmapSeries`, I am getting strange behavior and cannot locate the issue. 
would appreciate your help with that.

```
const xScale = scaleBand()
        .range([0, chartWidth])
        .domain(xDomain)
        .paddingInner(series.props.padding);
```
on the new FC, xScale range is set to a map of key to NaN.

2020-12-27 13:23 UTC, amcdnl requested changes

2020-12-27 13:23 UTC, amcdnl commented on src/Heatmap/CalendarHeatmap.tsx
> +  const { data: domainData, yDomain, xDomain, start } = getDataDomains();
This would be perfect for useMemo

2020-12-27 13:23 UTC, amcdnl commented on src/Heatmap/CalendarHeatmap.tsx
> +  // Format the xAxis label for the start + n week
Maybe this could be moved outside of the FC as a pure function.

2020-12-27 13:23 UTC, amcdnl commented on src/Heatmap/Heatmap.tsx
> +  //   ,
dead code

2020-12-27 13:23 UTC, amcdnl commented on src/Heatmap/Heatmap.tsx
> +    [data, xAxis, series]
You are missing some deps

2020-12-28 20:25 UTC, ynahmany commented
@amcdnl fixed all open issues.

2020-12-29 13:59 UTC, amcdnl approved these changes
LGTM - AWESOME STUFF!

2020-12-29 14:00 UTC, merged